//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoNguyenLighting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int CashID { get; set; }
        public string CashCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Activity { get; set; }
        public string Cashes { get; set; }
        public string Staff { get; set; }
        public string CollectorOrReceiver { get; set; }
        public string Contents { get; set; }
        public string Gender { get; set; }
    }
}
