//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoNguyenLighting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int UserID { get; set; }

        //[Required(ErrorMessage ="Please enter email",AllowEmptyStrings = false)]
        public string Email { get; set; }

        //[Required(ErrorMessage = "Please enter password", AllowEmptyStrings = false)]
        //[StringLength(100, ErrorMessage = "Password should be atleast 8 characters", MinimumLength = 8)]
        public string Password { get; set; }
        
        //[Required(ErrorMessage = "Please enter your name", AllowEmptyStrings = false)]
        public string Name { get; set; }

        //[Required(ErrorMessage = "Please enter your phone number", AllowEmptyStrings = false)]
        public string Phone { get; set; }
    }
}
